patch/0001-rubik-enable-GO111MODULE-and-Optimized-compilation-i.patch
patch/0002-rubik-fix-Dockerfile-build-failed.patch
patch/0003-set-the-burst-value-for-the-pod-to-enable-the-contai.patch
#end of file
